package com.hu.spider.led.dao;

import com.hu.spider.led.vo.LedLink;
import com.hu.spider.led.vo.LedLinkExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LedLinkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table led_link
     *
     * @mbg.generated Sat Dec 29 10:45:20 CST 2018
     */
    long countByExample(LedLinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table led_link
     *
     * @mbg.generated Sat Dec 29 10:45:20 CST 2018
     */
    int deleteByExample(LedLinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table led_link
     *
     * @mbg.generated Sat Dec 29 10:45:20 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table led_link
     *
     * @mbg.generated Sat Dec 29 10:45:20 CST 2018
     */
    int insert(LedLink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table led_link
     *
     * @mbg.generated Sat Dec 29 10:45:20 CST 2018
     */
    int insertSelective(LedLink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table led_link
     *
     * @mbg.generated Sat Dec 29 10:45:20 CST 2018
     */
    List<LedLink> selectByExample(LedLinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table led_link
     *
     * @mbg.generated Sat Dec 29 10:45:20 CST 2018
     */
    LedLink selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table led_link
     *
     * @mbg.generated Sat Dec 29 10:45:20 CST 2018
     */
    int updateByExampleSelective(@Param("record") LedLink record, @Param("example") LedLinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table led_link
     *
     * @mbg.generated Sat Dec 29 10:45:20 CST 2018
     */
    int updateByExample(@Param("record") LedLink record, @Param("example") LedLinkExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table led_link
     *
     * @mbg.generated Sat Dec 29 10:45:20 CST 2018
     */
    int updateByPrimaryKeySelective(LedLink record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table led_link
     *
     * @mbg.generated Sat Dec 29 10:45:20 CST 2018
     */
    int updateByPrimaryKey(LedLink record);
}