package com.hu.spider.led.vo;

public class LedLink {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column led_link.id
     *
     * @mbg.generated Sat Dec 29 10:45:20 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column led_link.link
     *
     * @mbg.generated Sat Dec 29 10:45:20 CST 2018
     */
    private String link;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column led_link.file_name
     *
     * @mbg.generated Sat Dec 29 10:45:20 CST 2018
     */
    private String fileName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column led_link.title
     *
     * @mbg.generated Sat Dec 29 10:45:20 CST 2018
     */
    private String title;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column led_link.id
     *
     * @return the value of led_link.id
     *
     * @mbg.generated Sat Dec 29 10:45:20 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column led_link.id
     *
     * @param id the value for led_link.id
     *
     * @mbg.generated Sat Dec 29 10:45:20 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column led_link.link
     *
     * @return the value of led_link.link
     *
     * @mbg.generated Sat Dec 29 10:45:20 CST 2018
     */
    public String getLink() {
        return link;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column led_link.link
     *
     * @param link the value for led_link.link
     *
     * @mbg.generated Sat Dec 29 10:45:20 CST 2018
     */
    public void setLink(String link) {
        this.link = link == null ? null : link.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column led_link.file_name
     *
     * @return the value of led_link.file_name
     *
     * @mbg.generated Sat Dec 29 10:45:20 CST 2018
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column led_link.file_name
     *
     * @param fileName the value for led_link.file_name
     *
     * @mbg.generated Sat Dec 29 10:45:20 CST 2018
     */
    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column led_link.title
     *
     * @return the value of led_link.title
     *
     * @mbg.generated Sat Dec 29 10:45:20 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column led_link.title
     *
     * @param title the value for led_link.title
     *
     * @mbg.generated Sat Dec 29 10:45:20 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    
	public LedLink() {
		super();
	}

	public LedLink(String link, String fileName, String title) {
		super();
		this.link = link;
		this.fileName = fileName;
		this.title = title;
	}

	public LedLink(Integer id, String link, String fileName, String title) {
		super();
		this.id = id;
		this.link = link;
		this.fileName = fileName;
		this.title = title;
	}

	@Override
	public String toString() {
		return "LedLink [id=" + id + ", link=" + link + ", fileName=" + fileName + ", title=" + title + "]";
	}
    
    
    
}